/**
 * デモ用シードデータ - 患者
 * 
 * 完全に架空の患者データ。
 * 本番環境のデータとは一切関係ありません。
 */

export const demoPatients = [
    {
        pId: 1,
        name: 'デモ 太郎',
        kana: 'デモ タロウ',
        gender: '男性',
        phone: '090-0000-0001',
        birthDate: new Date('1980-05-15'),
        memo: '腰痛で定期的に通院中。デスクワークが多い。',
        tags: JSON.stringify(['腰痛', '常連']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 2,
        name: 'サンプル 花子',
        kana: 'サンプル ハナコ',
        gender: '女性',
        phone: '090-0000-0002',
        birthDate: new Date('1975-08-22'),
        memo: '肩こりと眼精疲労。PC作業が原因か。',
        tags: JSON.stringify(['肩こり', '眼精疲労']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 3,
        name: 'テスト 次郎',
        kana: 'テスト ジロウ',
        gender: '男性',
        phone: '090-0000-0003',
        birthDate: new Date('1990-12-01'),
        memo: 'スポーツ後の膝痛。週1回の施術を希望。',
        tags: JSON.stringify(['膝痛', 'スポーツ']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 4,
        name: '架空 三子',
        kana: 'カクウ ミコ',
        gender: '女性',
        phone: '090-0000-0004',
        birthDate: new Date('1988-03-10'),
        memo: '妊娠中のマタニティケア。',
        tags: JSON.stringify(['マタニティ', '要配慮']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 5,
        name: '見本 四郎',
        kana: 'ミホン シロウ',
        gender: '男性',
        phone: '090-0000-0005',
        birthDate: new Date('1965-07-20'),
        memo: '高齢者向け全身ケア。血圧注意。',
        tags: JSON.stringify(['高齢者', '血圧注意']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 6,
        name: '例示 五郎',
        kana: 'レイジ ゴロウ',
        gender: '男性',
        phone: '090-0000-0006',
        birthDate: new Date('1995-02-28'),
        memo: '仕事終わりの夜間来院が多い。首の痛み。',
        tags: JSON.stringify(['首痛', '夜間希望']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 7,
        name: '試作 六美',
        kana: 'シサク ムツミ',
        gender: '女性',
        phone: '090-0000-0007',
        birthDate: new Date('2000-11-11'),
        memo: '学生。部活での怪我後のリハビリ。',
        tags: JSON.stringify(['学生', 'スポーツ']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 8,
        name: '仮名 七雄',
        kana: 'カメイ ナナオ',
        gender: '男性',
        phone: '090-0000-0008',
        birthDate: new Date('1978-06-05'),
        memo: 'ゴルフ肘の治療中。週末プレーヤー。',
        tags: JSON.stringify(['肘痛', 'ゴルフ']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 9,
        name: '標本 八重',
        kana: 'ヒョウホン ヤエ',
        gender: '女性',
        phone: '090-0000-0009',
        birthDate: new Date('1983-09-15'),
        memo: '産後の骨盤矯正。3ヶ月前に出産。',
        tags: JSON.stringify(['産後', '骨盤矯正']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
    {
        pId: 10,
        name: '模型 九太',
        kana: 'モケイ キュウタ',
        gender: '男性',
        phone: '090-0000-0010',
        birthDate: new Date('1958-04-01'),
        memo: '退職後の健康維持。月2回ペース。',
        tags: JSON.stringify(['高齢者', '健康維持']),
        attributes: '{}',
        externalRef: '{}',
        importMeta: '{}',
    },
];

